notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
services:
  - docker
python: 3
addons:
  apt:
    update: true
    packages:
      - jq
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - unzip
      - docker-ce
      - python3-pip
install: true
before_install:
  - which pip3    || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip # not pip3
  - which pip3    || echo 'which pip3 command failed.'
  - pip3 install --user $(whoami) --upgrade httpie
  - http --version --debug
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5432
jobs:
  include:
    # maven
    - stage: maven
      name: "Maven Java 11"
      jdk: openjdk11
      script:
        - docker pull postgres:alpine
        - docker run --rm -it -p 5432:5432 --name postgres postgres:alpine &
        - cd $TRAVIS_BUILD_DIR && ./mvnw clean test package
        - cd $TRAVIS_BUILD_DIR && java -jar target/*.jar &
        - wait_for 8080
        - http :8080 name=ololo
        - http :8080 name=trololo
        - http :8080
        - http delete :8080
        - http :8080
        - stop_any 80 8080
        - docker rm -f -v postgres
cache:
  directories:
    - ~/.m2
